import type { GetServerSideProps, NextPage } from 'next'
// import { PrismaClient } from '@prisma/client'
import Head from 'next/head'
import Image from 'next/image'
import { BestDeal } from '../components/BestDeal'
import FeatureSections from '../components/FeatureSections'
import { FindLocation } from '../components/FindLocation'
import Header from '../components/NavBar'
import PromoSection from '../components/PromoSection'
import { test_one } from '../constant/interfaces'
import styles from '../styles/Home.module.css'
import prisma from '../lib/prisma'

const Home = ({initialContacts}: {initialContacts: test_one[]}) => {

    console.log({initialContacts});
    

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <main className={styles.main}> */}
            <PromoSection />
            <BestDeal />
            <FindLocation />
            <FeatureSections />
            {/* </main> */}
        </div>
    )
}

// const prisma = new PrismaClient()

const getServerSideProps: GetServerSideProps = async ctx => {
    // const res = await fetch('https://.../posts')
    // const posts = await res.json()
    // const slug = ctx.params as QParams
console.log({msg: 'hello before prisma'});

    const contacts = await prisma.contact.findMany() as test_one[]

    console.log({contacts});
    
    return {
        props: {
            initialContacts: contacts
        }
    }
}

export {getServerSideProps}

export default Home
